name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore MonopolyTycoon.Domain.RuleEngine.sln

    - name: Build
      run: dotnet build MonopolyTycoon.Domain.RuleEngine.sln --no-restore --configuration Release

    - name: Test with Code Coverage
      run: |
        dotnet test MonopolyTycoon.Domain.RuleEngine.sln \
        --no-build \
        --configuration Release \
        --settings tests/CodeCoverage.runsettings \
        --logger "trx;LogFileName=test-results.trx" \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=cobertura \
        /p:CoverletOutput=./coverage.cobertura.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/MonopolyTycoon.Domain.RuleEngine.Tests/TestResults/test-results.trx

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-coverage-report
        path: ./coverage.cobertura.xml