name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MonopolyTycoon.sln

    - name: Build solution
      run: dotnet build MonopolyTycoon.sln --configuration Release --no-restore

    - name: Run Tests with Code Coverage
      run: dotnet test MonopolyTycoon.sln --no-build --configuration Release --settings tests/CodeCoverage.runsettings --collect:"XPlat Code Coverage"

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: tests/**/TestResults/**/*.cobertura.xml

    - name: Verify Code Coverage Threshold
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Required for private repos
        fail_ci_if_error: true
        verbose: true