name: .NET CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore MonopolyTycoon.sln

    - name: Build
      run: dotnet build MonopolyTycoon.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test MonopolyTycoon.sln --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --settings tests/coverlet.runsettings

    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: true